stages:
  - install
  - test
  - build
  - security
cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/

install_dependencies:
  stage: install
  image: node:20
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour

test:
  stage: test
  image: node:20
  services:
    - postgres:15
  variables:
    POSTGRES_DB: metro
    POSTGRES_USER: metro
    POSTGRES_PASSWORD: metro
    POSTGRES_HOST_AUTH_METHOD: trust
    PGHOST: postgres
    PGPORT: 5432
    PGUSER: metro
    PGPASSWORD: metro
    PGDATABASE: metro
  dependencies:
    - install_dependencies
  script:
    - npm test
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    IMAGE_LATEST: $CI_REGISTRY_IMAGE:latest
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $IMAGE_TAG -t $IMAGE_LATEST .
    - docker push $IMAGE_TAG
    - docker push $IMAGE_LATEST
  only:
    - main

security:npm-audit:
  stage: security
  image: node:18-alpine
  script:
    - npm audit --audit-level=moderate
  allow_failure: true

security:trivy:
  stage: security
  image:
    name : aquasec/trivy:latest
    entrypoint: [""]
  script:
    - trivy image --severity HIGH,CRITICAL $CI_REGISTRY_IMAGE:latest
  only:
    - main