stages:
  - install
  - test
  - build

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/

install_dependencies:
  stage: install
  image: node:20
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour

test:
  stage: test
  image: node:20
  services:
    - postgres:15
  variables:
    POSTGRES_DB: test_db
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_HOST_AUTH_METHOD: trust
    PGHOST: postgres
    PGPORT: 5432
    PGUSER: postgres
    PGPASSWORD: postgres
    PGDATABASE: test_db
  dependencies:
    - install_dependencies
  script:
    - npm test
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

build:
  stage: build
  image: node:20
  dependencies:
    - install_dependencies
  script:
    - echo "Build completed successfully"
  only:
    - main
    - Phase-1-Database
