services:
    api:
        image: registry.gitlab.com/erwanmarega/api_metro_marega:latest
        env_file:
            - .env.staging
        environment:
            - NODE_ENV=staging
        ports:
            - "3001:3000"
        restart: unless-stopped
        extra_hosts:
            - "host.docker.internal:host-gateway"